name: Create Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - v*

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: ->actions/checkout@v4
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ->actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm install

      - name: ->npx changelogithub
        run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}

      - name: ->googleapis/release-please-action@v4
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
      # - run: npm ci
      #   if: ${{ steps.release.outputs.release_created }}
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   if: ${{ steps.release.outputs.release_created }}
